servers:
- branch: raw-add-inputs
  hostname: clnode091.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.1
  run: true
- branch: raw-add-inputs
  hostname: clnode049.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.2
  run: true
- branch: raw-add-inputs
  hostname: clnode044.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.3
  run: true
- branch: raw-add-inputs
  hostname: clnode065.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.4
  run: true
- branch: raw-add-inputs
  hostname: clnode042.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.5
  run: true
- branch: raw-add-inputs
  hostname: clnode073.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.6
  run: true
- branch: raw-add-inputs
  hostname: clnode076.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.7
  run: true
- branch: raw-add-inputs
  hostname: clnode090.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.8
  run: true
- branch: raw-add-inputs
  hostname: clnode041.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.9
  run: true
- branch: raw-add-inputs
  hostname: clnode057.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.10
  run: true