servers:
  - branch: raw-add-inputs
    hostname: c220g5-110414.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.1
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110431.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.2
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110420.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.3
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-120129.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.4
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-120118.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.5
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110429.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.6
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110422.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.7
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110929.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.8
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110920.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.9
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110901.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.10
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-120124.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.11
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110924.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.12
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110417.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.13
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110404.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.14
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110406.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.15
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110412.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.16
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110418.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.17
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-120121.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.18
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110909.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.19
    run: true
  - branch: raw-add-inputs
    hostname: c220g5-110427.wisc.cloudlab.us
    redis: true
    redis_ip: 10.10.1.20
    run: true