servers:
  - hostname: c220g1-031126.wisc.cloudlab.us
    branch: network-state
    redis: true

  - hostname: c220g1-031122.wisc.cloudlab.us
    branch: network-state
    redis: true

  - hostname: c220g1-031114.wisc.cloudlab.us
    branch: network-state
    redis: true

  - hostname: c220g1-031116.wisc.cloudlab.us
    branch: network-state
    redis: true

  - hostname: c220g1-031115.wisc.cloudlab.us
    branch: network-state
    redis: true