# SSH username for connecting to servers (set to your SSH user)
username: janechen
servers:
- branch: unum-adaptor
  hostname: clnode036.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.1
  run: false
- branch: unum-adaptor
  hostname: clnode159.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.2
  run: false
- branch: unum-adaptor
  hostname: clnode023.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.3
  run: false
- branch: unum-adaptor
  hostname: clnode189.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.4
  run: false
- branch: unum-adaptor
  hostname: clnode171.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.5
  run: false
- branch: unum-adaptor
  hostname: clnode034.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.6
  run: false
- branch: unum-adaptor
  hostname: sm110p-10s10611.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.1
  run: false
- branch: unum-adaptor
  hostname: sm110p-10s10619.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.2
  run: false
- branch: unum-adaptor
  hostname: clnode153.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.1
  run: false
- branch: unum-adaptor
  hostname: clnode125.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.2
  run: false
- branch: unum-adaptor
  hostname: clnode251.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.3
  run: false
- branch: unum-adaptor
  hostname: clnode151.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.4
  run: false
- branch: unum-adaptor
  hostname: clnode228.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.5
  run: false
- branch: unum-adaptor
  hostname: clnode163.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.6
  run: false
- branch: unum-adaptor
  hostname: clnode106.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.7
  run: false
- branch: unum-adaptor
  hostname: clnode100.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.8
  run: false
- branch: unum-adaptor
  hostname: clnode099.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.9
  run: false
- branch: unum-adaptor
  hostname: clnode072.clemson.cloudlab.us
  redis: true
  redis_ip: 10.10.1.10
  run: false
- branch: unum-adaptor
  hostname: c220g1-031116.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.1
  run: false
- branch: unum-adaptor
  hostname: c220g1-031114.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.2
  run: false
- branch: unum-adaptor
  hostname: c220g1-031122.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.3
  run: false
- branch: unum-adaptor
  hostname: c220g1-031115.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.4
  run: false
- branch: unum-adaptor
  hostname: c220g1-031126.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.5
  run: false
- branch: unum-adaptor
  hostname: c220g2-011122.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.6
  run: false
- branch: unum-adaptor
  hostname: c220g5-111324.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.7
  run: false
- branch: unum-adaptor
  hostname: c220g1-030807.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.8
  run: false
- branch: unum-adaptor
  hostname: c220g5-111331.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.9
  run: false
- branch: unum-adaptor
  hostname: c220g5-111328.wisc.cloudlab.us
  redis: true
  redis_ip: 10.10.1.10
  run: false
