servers:
  - hostname: clnode166.clemson.cloudlab.us
    branch: unum-adaptor
    redis: true
    run: true
    redis_ip: 10.10.1.1

  - hostname: clnode036.clemson.cloudlab.us
    branch: unum-adaptor
    redis: true
    run: false
    redis_ip: 10.10.1.2

  - hostname: clnode007.clemson.cloudlab.us
    branch: unum-adaptor
    redis: true
    run: false
    redis_ip: 10.10.1.3

  # - hostname: clstore04.clemson.cloudlab.us
  #   branch: unum-adaptor
  #   redis: true
  #   run: false
  #   redis_ip: 10.10.1.4

  # - hostname: clstore02.clemson.cloudlab.us
  #   branch: unum-adaptor
  #   redis: true
  #   run: false
  #   redis_ip: 10.10.1.5

  - hostname: clnode165.clemson.cloudlab.us
    branch: unum-adaptor
    redis: true
    run: false
    redis_ip: 10.10.1.6

  - hostname: clnode189.clemson.cloudlab.us
    branch: unum-adaptor
    redis: true
    run: false
    redis_ip: 10.10.1.7

  - hostname: clnode034.clemson.cloudlab.us
    branch: unum-adaptor
    redis: true
    run: false
    redis_ip: 10.10.1.8

  - hostname: clnode099.clemson.cloudlab.us
    branch: unum-adaptor
    redis: true
    run: false
    redis_ip: 10.10.1.9

  - hostname: clnode023.clemson.cloudlab.us
    branch: unum-adaptor
    redis: true
    run: false
    redis_ip: 10.10.1.10
